# -*- coding: utf-8 -*-
"""signal_functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bh95PvV_hn72Hm5RYQbWYCyhIFpE7_LY
"""

import numpy as np

def Z_t(lamb):
    """Poisson jump process"""
    n_jumps = np.random.poisson(lamb)
    if n_jumps == 0:
        return 0.0
    jumps = np.random.normal(0, 1, n_jumps)
    return np.sum(jumps)

def sinusoidal_signal(t):
    A = np.random.uniform(0.5, 10.0)
    f = np.random.uniform(0.1, 1.0)
    phi = np.random.uniform(0, 2 * np.pi)
    return A * np.sin(2 * np.pi * f * t + phi)

def damped_oscillation(t):
    A = np.random.uniform(0.5, 20.0)
    alpha = np.random.uniform(1.0, 5.0)
    f = np.random.uniform(1.0, 5.0)
    phi = np.random.uniform(0, 2 * np.pi)
    return A * np.exp(-alpha * t) * np.sin(2 * np.pi * f * t + phi)

def square_wave(t):
    A = np.random.uniform(0.1, 20.0)
    f = 1.0
    phi = np.random.uniform(0, 2 * np.pi)
    return A * np.sign(np.sin(2 * np.pi * f * t + phi))

def triangular_wave(t):
    A = np.random.uniform(0.3, 10.0)
    f = 1.0
    return A * np.abs(2 * (f * t - np.floor(f * t + 0.5)))

def sawtooth_wave(t):
    A = np.random.uniform(0.1, 20.0)
    f = 1.0
    return A * (f * t - np.floor(f * t + 0.5))

def gaussian_pulse(t):
    A = np.random.uniform(0.5, 20.0)
    mu = np.random.uniform(0.3, 0.7)
    sigma = np.random.uniform(0.05, 0.2)
    return A * np.exp(-(t - mu) ** 2 / (2 * sigma ** 2))

def chirp_signal(t):
    A = np.random.uniform(0.5, 20.0)
    f0 = np.random.uniform(1.0, 5.0)
    k = np.random.uniform(1.0, 4.0)
    return A * np.sin(2 * np.pi * (f0 * t + (k / 2) * t ** 2))

def single_pulse(t):
    pulse_width = np.random.uniform(0.05, 1)
    t_start = np.random.uniform(0, 1 - pulse_width)
    signal = np.zeros_like(t)
    signal[(t >= t_start) & (t < t_start + pulse_width)] = np.random.uniform(0.05, 10.2)
    return signal

ALL_SIGNAL_FUNCS = [
    sinusoidal_signal, square_wave, sawtooth_wave, triangular_wave,
    damped_oscillation, gaussian_pulse, chirp_signal, single_pulse
]

def generate_signals(n_samples_per_func, M, noise_eps=0.01, lamb=1.0, T=1.0, signal_funcs=None):
    if signal_funcs is None:
        signal_funcs = ALL_SIGNAL_FUNCS
    total_points = int(M * T)
    t = np.linspace(0, T, total_points)
    dt = t[1] - t[0]

    Y_list, S_list = [], []
    for func in signal_funcs:
        S_clean = func(t)
        for _ in range(n_samples_per_func):
            y = np.zeros(total_points)
            for k in range(1, total_points):
                dw = np.random.normal(0, np.sqrt(dt))
                y[k] = y[k-1] + S_clean[k-1] * dt + noise_eps * (dw + Z_t(lamb))
            Y_list.append(y)
            S_list.append(S_clean)

    return np.array(Y_list, dtype=np.float32), np.array(S_list, dtype=np.float32)